import createClient from "openapi-fetch";
import type { paths,components } from "../../schema"; // generated by openapi-typescript

const api = createClient<paths>({ baseUrl: "http://127.0.0.1:8000" });

export default api ; 

export type DoctorCategory = components['schemas']["DoctorCategoryResponse"];