import createClient from "openapi-fetch";
import type { paths,components } from "../../schema"; // generated by openapi-typescript

const api = createClient<paths>({ baseUrl: "https://bimonet.com" });

export default api ; 

export type DoctorCategory = components['schemas']["DoctorCategoryResponse"];